spring:
  application:
    name: conversational-agents

  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: validate       # Flyway owns schema everywhere

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    # baseline-on-migrate: true   # uncomment if migrating an existing DB

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

# LangChain4j (no secrets here)
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: ${OPENAI_MODEL:gpt-4o-mini}

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
